class DistrictModel {
  final int id;
  final String value;
  final String label;
  final String parentId;
  final String country;
  final String ISOcode;

  DistrictModel({
    required this.id,
    required this.value,
    required this.label,
    required this.parentId,
    required this.country,
    required this.ISOcode,
  });
}

List<DistrictModel> districts = [
  DistrictModel(
    id: 1,
    value: 'Bandarban',
    label: 'Bandarban',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 2,
    value: 'Barguna',
    label: 'Barguna',
    parentId: 'Barisal',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 3,
    value: 'Barishal',
    label: 'Barishal',
    parentId: 'Barisal',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 4,
    value: 'Bhola',
    label: 'Bhola',
    parentId: 'Barisal',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 5,
    value: 'Bogura',
    label: 'Bogura (previously known as Bogra)',
    parentId: 'Rajshahi',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 6,
    value: 'Brahmanbaria',
    label: 'Brahmanbaria',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 7,
    value: 'Chandpur',
    label: 'Chandpur',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 8,
    value: 'Chattogram',
    label: 'Chattogram ',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 9,
    value: 'Chuadanga',
    label: 'Chuadanga',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 10,
    value: 'Comilla',
    label: 'Comilla ',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 11,
    value: "Cox's Bazar",
    label: "Cox's Bazar",
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BD',
  ),
  DistrictModel(
    id: 12,
    value: 'Dhaka',
    label: 'Dhaka',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 13,
    value: 'Dinajpur',
    label: 'Dinajpur',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 14,
    value: 'Faridpur',
    label: 'Faridpur',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 15,
    value: 'Feni',
    label: 'Feni',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 16,
    value: 'Gaibandha',
    label: 'Gaibandha',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 17,
    value: 'Gazipur',
    label: 'Gazipur',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 18,
    value: 'Gopalganj',
    label: 'Gopalganj',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 19,
    value: 'Habiganj',
    label: 'Habiganj',
    parentId: 'Sylhet',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 20,
    value: 'Jamalpur',
    label: 'Jamalpur',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 21,
    value: 'Jashore',
    label: 'Jashore ',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 22,
    value: 'Jhalokati',
    label: 'Jhalokati',
    parentId: 'Barisal',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 23,
    value: 'Jhenaidah',
    label: 'Jhenaidah',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 24,
    value: 'Joypurhat',
    label: 'Joypurhat',
    parentId: 'Rajshahi',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 25,
    value: 'Khagrachari',
    label: 'Khagrachari',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 26,
    value: 'Khulna',
    label: 'Khulna',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 27,
    value: 'Kishoreganj',
    label: 'Kishoreganj',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 28,
    value: 'Kurigram',
    label: 'Kurigram',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 29,
    value: 'Kushtia',
    label: 'Kushtia',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 30,
    value: 'Lakshmipur',
    label: 'Lakshmipur',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 31,
    value: 'Lalmonirhat',
    label: 'Lalmonirhat',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 32,
    value: 'Madaripur',
    label: 'Madaripur',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 33,
    value: 'Magura',
    label: 'Magura',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 34,
    value: 'Manikganj',
    label: 'Manikganj',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 35,
    value: 'Meherpur',
    label: 'Meherpur',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 36,
    value: 'Moulvibazar',
    label: 'Moulvibazar',
    parentId: 'Sylhet',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 37,
    value: 'Munshiganj',
    label: 'Munshiganj',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 38,
    value: 'Mymensingh',
    label: 'Mymensingh',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 39,
    value: 'Naogaon',
    label: 'Naogaon',
    parentId: 'Rajshahi',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 40,
    value: 'Narail',
    label: 'Narail',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 41,
    value: 'Narayanganj',
    label: 'Narayanganj',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 42,
    value: 'Narsingdi',
    label: 'Narsingdi',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 43,
    value: 'Natore',
    label: 'Natore',
    parentId: 'Rajshahi',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 44,
    value: 'Netrokona',
    label: 'Netrokona',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 45,
    value: 'Nilphamari',
    label: 'Nilphamari',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 46,
    value: 'Noakhali',
    label: 'Noakhali',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 47,
    value: 'Pabna',
    label: 'Pabna',
    parentId: 'Rajshahi',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 48,
    value: 'Panchagarh',
    label: 'Panchagarh',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 49,
    value: 'Patuakhali',
    label: 'Patuakhali',
    parentId: 'Barisal',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 50,
    value: 'Pirojpur',
    label: 'Pirojpur',
    parentId: 'Barisal',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 51,
    value: 'Rajbari',
    label: 'Rajbari',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 52,
    value: 'Rajshahi',
    label: 'Rajshahi',
    parentId: 'Rajshahi',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 53,
    value: 'Rangamati',
    label: 'Rangamati',
    parentId: 'Chittagong',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 54,
    value: 'Rangpur',
    label: 'Rangpur',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 55,
    value: 'Satkhira',
    label: 'Satkhira',
    parentId: 'Khulna',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 56,
    value: 'Shariatpur',
    label: 'Shariatpur',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 57,
    value: 'Sherpur',
    label: 'Sherpur',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 58,
    value: 'Sirajganj',
    label: 'Sirajganj',
    parentId: 'Rajshahi',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 59,
    value: 'Sunamganj',
    label: 'Sunamganj',
    parentId: 'Sylhet',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 60,
    value: 'Sylhet',
    label: 'Sylhet',
    parentId: 'Sylhet',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 61,
    value: 'Tangail',
    label: 'Tangail',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 62,
    value: 'Thakurgaon',
    label: 'Thakurgaon',
    parentId: 'Rangpur',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 63,
    value: 'Jamalpur',
    label: 'Jamalpur',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
  DistrictModel(
    id: 64,
    value: 'Narsingdi',
    label: 'Narsingdi',
    parentId: 'Dhaka',
    country: 'Bangladesh',
    ISOcode: 'BDT',
  ),
];
